services:

  db:
    container_name: db
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:${REDIS_PORT}"
    volumes:
      - redis_data:/data

  habit_tracker_backend:
    container_name: habit_tracker
    build:
      context: .
      dockerfile: docker/habit_tracker/Dockerfile
    env_file:
      .env
    ports:
      - "${API_PORT}:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
  
volumes:
  postgres_data:
  redis_data:
